name: note_deid_20180831
deidJobs:
  - jobName: stanford_deid_v1_strict
    version: v1.5
    textFields: fullnote
    textIdFields: note_id
    analytic: true
    dateJitter: local
    dateJitterRange: 30
    dateJitterSeedField: pat_id
    googleDlpEnabled: false
    nerEnabled: true
    googleDlpInfoTypes:
#      - itemName: age
#        infoTypes: AGE
      - itemName: date
        infoTypes: DATE
        actionParam: ''
        fields: 'jitter'
      - itemName: phi_date
        infoTypes: DATE_OF_BIRTH
        actionParam: ''
        fields: 'jitter'
      - itemName: payment_id
        infoTypes: CREDIT_CARD_NUMBER,CREDIT_CARD_TRACK_NUMBER,US_BANK_ROUTING_MICR,AMERICAN_BANKERS_CUSIP_ID,IBAN_CODE
        actionParam: 999999999999999
      - itemName: public_id
        infoTypes: US_ADOPTION_TAXPAYER_IDENTIFICATION_NUMBER,US_DRIVERS_LICENSE_NUMBER,US_INDIVIDUAL_TAXPAYER_IDENTIFICATION_NUMBER,US_PREPARER_TAXPAYER_IDENTIFICATION_NUMBER,US_PASSPORT,SWIFT_CODE
        actionParam: 999999999
      - itemName: patient_ssn
        infoTypes: US_SOCIAL_SECURITY_NUMBER
        actionParam: 999-99-9999
      - itemName: other_id
        infoTypes: US_EMPLOYER_IDENTIFICATION_NUMBER,US_VEHICLE_IDENTIFICATION_NUMBER,IMEI_HARDWARE_ID
        actionParam: 999999999
      - itemName: other_email
        infoTypes: EMAIL_ADDRESS
        actionParam: deidentified@example.com
      - itemName: other_name
        infoTypes: PERSON_NAME
      - itemName: other_phone
        infoTypes: PHONE_NUMBER,US_TOLLFREE_PHONE_NUMBER
      - itemName: care_provider_id
        infoTypes: US_HEALTHCARE_NPI,US_DEA_NUMBER
        actionParam: 9999999999999
      - itemName: other_address
        infoTypes: LOCATION,STREET_ADDRESS
      - itemName: internet_locator
        infoTypes: IP_ADDRESS,MAC_ADDRESS,URL

    spec:

#      - itemName: phi_date
#        action: jitter_date_from_field
#        actionParam: ''
#        fields: 'jitter'

#      - itemName: age
#        action: remove_age
#        fields: ''

      - itemName: mrn
        action: remove_mrn
        actionParam: [mrn]
        fields: ''

      - itemName: patient_mrn
        action: replace_minimumlengthword_with
        actionParam: [mrn] 3
        fields:  PAT_MRN_ID

      - itemName: other_id
        action: replace_minimumlengthword_with
        actionParam: [id] 3
        fields:  pat_id, birth_wrist_band, epic_pat_id, PRIM_CVG_ID, PRIM_EPP_ID, EMPLOYER_ID

      - itemName: general
        action: general
        actionParam:
        actionParamMap: {"general-phone":"[phone]","general-email":"[email]","general-ip":"[ip address]","general-url":"[url]","general-ssn":"[ssn]"}
        fields:

      - itemName: patient_ssn
        action: replace_minimumlengthword_with
        actionParam: [ssn] 4
        fields:  ssn

      - itemName: patient_email
        action: replace_minimumlengthword_with
        actionParam: [patient_email] 3
        fields:  email_address

      - itemName: other_email
        action: replace_minimumlengthword_with
        actionParam: [email] 3
        fields:

      - itemName: public_id
        action: replace_minimumlengthword_with
        actionParam: [public_id] 3
        fields:  medicare_num, medicaid_num

      - itemName: family_id
        action: replace_minimumlengthword_with
        actionParam: [family_id] 3
        fields:  mother_pat_id, father_pat_id

      - itemName: patient_name
        action: surrogate_name
        actionParamMap: {"format":"L,F","f_zip":"zip","f_gender":"","f_dob":"birth_date"}
        fields:  pat_name, PROXY_NAME

      - itemName: patient_name
        action: surrogate_name
        actionParamMap: {"format":"F","f_zip":"zip","f_gender":"","f_dob":"birth_date"}
        fields:  PAT_FIRST_NAME

      - itemName: patient_name
        action: surrogate_name
        actionParamMap: {"format":"L","f_zip":"zip","f_gender":"","f_dob":"birth_date"}
        fields:  PAT_LAST_NAME, PAT_MIDDLE_NAME


      - itemName: other_name
        action: replace_minimumlengthword_with
        actionParam: [name] 1
        fields: GUARDIAN_NAME

      - itemName: emergency_contact
        action: replace_strictly_with
        actionParam: [emergency_contact]
        fields: father_name, mother_name

      - itemName: other_address
        action: surrogate_address
        fields:  ''

      - itemName: patient_address
        action: surrogate_address
        actionParamMap: {"f_address_1":"add_line_1","f_address_2":"add_line_2", "f_city":"city", "f_zip":"zip"}
        fields: ''

      - itemName: patient_address
        action: surrogate_address
        actionParamMap: {"f_address_1":"tmp_addr_line_1","f_address_2":"tmp_addr_line_2", "f_city":"tmp_city", "f_zip":"tmp_zip"}
        fields: ''


      - itemName: emergency_contact_address
        action: surrogate_address
        actionParamMap: {"f_address_1":"father_addr_ln_1","f_address_2":"father_addr_ln_2", "f_city":"father_city", "f_zip":"father_zip"}
        fields: ''

      - itemName: emergency_contact_address
        action: surrogate_address
        actionParamMap: {"f_address_1":"mother_addr_ln_1","f_address_2":"mother_addr_ln_2", "f_city":"mother_city", "f_zip":"mother_zip"}
        fields: ''

      - itemName: patient_phone
        action: replace_minimumlengthword_with
        actionParam: [patient_phone] 7
        fields:  home_phone, work_phone, tmp_home_phone, PROXY_PHONE,

      - itemName: emergency_contact_phone
        action: replace_minimumlengthword_with
        actionParam: [mergency_contact_phone] 7
        fields: father_cell_phone, mother_cell_phone

      - itemName: accession_num
        action: replace_minimumlengthword_with
        actionParam: [accession_number] 5
        fields: accession_num

      - itemName: general_name
        action: surrogate_name
        fields: ''
