name: note_deid_20180831
deidJobs:
  - jobName: stanford_deid_v1_strict
    version: v1.5
    analytic: true
    dateJitter: local
    dateJitterRange: 30
    dateJitterSeedField: pat_id
    googleDlpEnabled: false
    nerEnabled: true
    googleDlpInfoTypes:
#      - itemName: age
#        infoTypes: AGE
      - itemName: date
        infoTypes: DATE
        actionParam: ''
        fields: 'jitter'
      - itemName: phi_date
        infoTypes: DATE_OF_BIRTH
        actionParam: ''
        fields: 'jitter'
      - itemName: payment_id
        infoTypes: CREDIT_CARD_NUMBER,CREDIT_CARD_TRACK_NUMBER,US_BANK_ROUTING_MICR,AMERICAN_BANKERS_CUSIP_ID,IBAN_CODE
        actionParam: 999999999999999
      - itemName: public_id
        infoTypes: US_ADOPTION_TAXPAYER_IDENTIFICATION_NUMBER,US_DRIVERS_LICENSE_NUMBER,US_INDIVIDUAL_TAXPAYER_IDENTIFICATION_NUMBER,US_PREPARER_TAXPAYER_IDENTIFICATION_NUMBER,US_PASSPORT,SWIFT_CODE
        actionParam: 999999999
      - itemName: patient_ssn
        infoTypes: US_SOCIAL_SECURITY_NUMBER
        actionParam: 999-99-9999
      - itemName: other_id
        infoTypes: US_EMPLOYER_IDENTIFICATION_NUMBER,US_VEHICLE_IDENTIFICATION_NUMBER,IMEI_HARDWARE_ID
        actionParam: 999999999
      - itemName: other_email
        infoTypes: EMAIL_ADDRESS
        actionParam: deidentified@example.com
      - itemName: other_name
        infoTypes: PERSON_NAME
      - itemName: other_phone
        infoTypes: PHONE_NUMBER,US_TOLLFREE_PHONE_NUMBER
      - itemName: care_provider_id
        infoTypes: US_HEALTHCARE_NPI,US_DEA_NUMBER
        actionParam: 9999999999999
      - itemName: other_address
        infoTypes: LOCATION,STREET_ADDRESS
      - itemName: internet_locator
        infoTypes: IP_ADDRESS,MAC_ADDRESS,URL

    spec:
      - itemName: phi_date
        action: jitter_date
        actionParam: gf2jKlYrX6
        fields: ''

      - itemName: age
        action: remove_age
        fields: ''

      - itemName: mrn
        action: remove_mrn
        fields: ''

      - itemName: general
        action: general
        actionParam:
        actionParamMap: {"general-phone":"999-999-9999","general-email":"99999","general-ip":"000.000.000.000","general-url":"www.example.com","general-ssn":"999-99-9999"}

        fields:

      - itemName: general_name
        action: surrogate_name
        fields: ''

      - itemName: other_address
        action: surrogate_address
        fields:  ''
